# SPDX-FileCopyrightText: Alex Turbov <zaufi@pm.me>
# SPDX-License-Identifier: CC0-1.0
#
# See docs here:
# https://github.com/DavidAnson/markdownlint/blob/main/README.md#rules--aliases

default: true

# Multiple consecutive blank lines
MD012:
  maximum: 2

# Line length
MD013:
  line_length: 100
  tables: false

# Multiple headings with the same content
MD024:
  siblings_only: true

# Code fence style
MD048:
  style: backtick

# Emphasis style
MD049:
  style: underscore

# Strong style
MD050:
  style: asterisk
